### ISSUE TITLE
Mixed content error 

### ISSUE THREAD

**Issue by Alex61NN5** [opendecide/ngx-segment-analytics#64]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
```

### OS and Version?
 Windows 10

### Tools Version
node: 9.2.1
npm: 6.4.1

### The log given by the failure.
Mixed Content: The page at 'https://www.mywebsite.com/' was loaded over HTTPS, but requested an insecure script 'http://cdn.segment.com/analytics.js/v1/8ecKAAbQ3S90lKLXsBmEzYsSvwts63HJ/analytics.min.js'. This request has been blocked; the content must be served over HTTPS.

### Angular Version
```
Angular CLI: 6.2.1
Node: 9.2.1
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.8.1 (cli-only)
@angular/cli                      6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.8.1 (cli-only)
@schematics/update                0.8.1 (cli-only)
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.8.3
```

### Mention any other details that might be useful.
Hey there,

I am running this on my app, it works but for some reason I keep getting this mixed content error?? I am running this on an angular universal application do you think that could be contributing to this error?? I am running my website on heroku with `https://` but for some reason the segment script returned by this module is using `http://`

**Comment by guillaume-ro-fr** [comment]
Hey @Alex61NN5,

Thanks for your report.

It's a weird error because [the test](https://github.com/opendecide/ngx-segment-analytics/blob/6392170fd9f73f9a1af0105a3717e505b0904aed/src/ngx-segment-analytics.service.ts#L74-L75) for the protocol setting is using the browser protocol.

Do you SSR with Angular Universal ? What is your browser version ?

**Comment by Alex61NN5** [comment]
Hey,

Thanks for the response.

So my site is running SSR could that be the issue?? I saw in the docs that this library supports Angular Universal I assumed that also meant SSR.

I am currently getting the error in chrome and safari, I havent tested firefox though

Thanks

**Comment by guillaume-ro-fr** [comment]
This library support Angular Universal and by extension SSR (I use it myself this way), but I don't if Node (or Domino) don't change the `doc.location.protocol` property, depending on your configuration.

I never see this error before.

Can you paste your `server.ts` configuration ? To see if there is any configuration related to Domino or Node.

**Comment by Alex61NN5** [comment]
This is my **server.ts**

```
// These are important and needed before anything else
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import { enableProdMode } from '@angular/core';
import * as express from 'express';
import { join } from 'path';
const path = require('path');

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// SSL Redirect
const sslRedirect = require('heroku-ssl-redirect');
// Compression
const compression = require('compression');
// Express server
const app = express();

const PORT = process.env.PORT || 8080;
const DIST_FOLDER = join(process.cwd(), 'dist');
const APP_NAME = 'browser';

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main');

// Express Engine
import { ngExpressEngine } from '@nguniversal/express-engine';
// Import module map for lazy loading
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

app.use(sslRedirect());
app.use(compression());

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, APP_NAME));

// TODO: implement data requests securely
app.get('/api/*', (req, res) => {
  res.status(404).send('data requests are not supported');
});

// Server static files from /browser
app.get('*.*', express.static(join(DIST_FOLDER, APP_NAME), {
  maxAge: '1y'
}));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.render('index', { req });
});

app.route('/sitemap.xml')
  .get((req, res) => {
    res.sendFile(path.resolve(path.join(__dirname, '/sitemap.xml')));
  });

app.route('/robots.txt')
  .get((req, res) => {
    res.sendFile(path.resolve(path.join(__dirname, '/robots.txt')));
  });

// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node server listening on http://localhost:${PORT}`);
});
```

**Comment by Alex61NN5** [comment]
Any update on this? do you need any more information?

**Comment by Alex61NN5** [comment]
My app is being run on Heroku could that be causing an issue?

**Comment by Alex61NN5** [comment]
I have forked the repo and removed the code that determines whether to use `http` or `https`, and have changed it to force the use of https. This has solved my issue so I am closing this ticket

**Comment by guillaume-ro-fr** [comment]
Thanks @Alex61NN5 !

I've disabled the insecure loading with HTTP, I don't see why we should leave it...
